//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.QLTS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.QLTS.Common.Resource.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e001.
        /// </summary>
        public static string e001 {
            get {
                return ResourceManager.GetString("e001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e002.
        /// </summary>
        public static string e002 {
            get {
                return ResourceManager.GetString("e002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e003.
        /// </summary>
        public static string e003 {
            get {
                return ResourceManager.GetString("e003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e004.
        /// </summary>
        public static string e004 {
            get {
                return ResourceManager.GetString("e004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e005.
        /// </summary>
        public static string e005 {
            get {
                return ResourceManager.GetString("e005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e006.
        /// </summary>
        public static string e006 {
            get {
                return ResourceManager.GetString("e006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e007.
        /// </summary>
        public static string e007 {
            get {
                return ResourceManager.GetString("e007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e008.
        /// </summary>
        public static string e008 {
            get {
                return ResourceManager.GetString("e008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e009.
        /// </summary>
        public static string e009 {
            get {
                return ResourceManager.GetString("e009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e010.
        /// </summary>
        public static string e010 {
            get {
                return ResourceManager.GetString("e010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e011.
        /// </summary>
        public static string e011 {
            get {
                return ResourceManager.GetString("e011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e012.
        /// </summary>
        public static string e012 {
            get {
                return ResourceManager.GetString("e012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e013.
        /// </summary>
        public static string e013 {
            get {
                return ResourceManager.GetString("e013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e014.
        /// </summary>
        public static string e014 {
            get {
                return ResourceManager.GetString("e014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e015.
        /// </summary>
        public static string e015 {
            get {
                return ResourceManager.GetString("e015", resourceCulture);
            }
        }
    }
}
