//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.QLTS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceProcedure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceProcedure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.QLTS.Common.Resource.ResourceProcedure", typeof(ResourceProcedure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_FixedAsset_CheckDuplicateAssetCode_Create.
        /// </summary>
        public static string CheckDuplicateCodeAssetCreate {
            get {
                return ResourceManager.GetString("CheckDuplicateCodeAssetCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_FixedAsset_CheckDuplicateAssetCode_Update.
        /// </summary>
        public static string CheckDuplicateCodeAssetUpdate {
            get {
                return ResourceManager.GetString("CheckDuplicateCodeAssetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Fixed_asset_CheckDuplication_IncrementCode_Create.
        /// </summary>
        public static string CheckDuplicationIncrementCodeCreate {
            get {
                return ResourceManager.GetString("CheckDuplicationIncrementCodeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Fixed_asset_CheckDuplication_IncrementCode_Update.
        /// </summary>
        public static string CheckDuplicationIncrementCodeUpdate {
            get {
                return ResourceManager.GetString("CheckDuplicationIncrementCodeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_fixed_asset_Increment_Detail_Create.
        /// </summary>
        public static string CreateAssetIncrementDetail {
            get {
                return ResourceManager.GetString("CreateAssetIncrementDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_fixed_asset_IncrementDetail_Delete.
        /// </summary>
        public static string DeleteAssetIncrementDetail {
            get {
                return ResourceManager.GetString("DeleteAssetIncrementDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_fixed_asset_IncrementDetail_Delete.
        /// </summary>
        public static string DeleteIncrementDetail {
            get {
                return ResourceManager.GetString("DeleteIncrementDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Delete_Record.
        /// </summary>
        public static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetAll_Record.
        /// </summary>
        public static string GetAllRecord {
            get {
                return ResourceManager.GetString("GetAllRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_fixed_asset_GetDetail_Multi.
        /// </summary>
        public static string GetAssetByIncrement {
            get {
                return ResourceManager.GetString("GetAssetByIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Asset_Multi.
        /// </summary>
        public static string GetAssetCache {
            get {
                return ResourceManager.GetString("GetAssetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Fixed_Asset_Detail.
        /// </summary>
        public static string GetAssetDetail {
            get {
                return ResourceManager.GetString("GetAssetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Fixed_Asset_Increment_Detail.
        /// </summary>
        public static string GetAssetIncrementDetail {
            get {
                return ResourceManager.GetString("GetAssetIncrementDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_FixedAsset_Increment_GetName.
        /// </summary>
        public static string GetAssetIncrementName {
            get {
                return ResourceManager.GetString("GetAssetIncrementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_asset_increment_GetPaging.
        /// </summary>
        public static string GetAssetIncrementPaging {
            get {
                return ResourceManager.GetString("GetAssetIncrementPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_asset_GetPaging.
        /// </summary>
        public static string GetAssetPaging {
            get {
                return ResourceManager.GetString("GetAssetPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_NewCode.
        /// </summary>
        public static string GetNewCode {
            get {
                return ResourceManager.GetString("GetNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Search_record.
        /// </summary>
        public static string SearchRecord {
            get {
                return ResourceManager.GetString("SearchRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Update_Budget.
        /// </summary>
        public static string UpdateBudget {
            get {
                return ResourceManager.GetString("UpdateBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Fixed_Asset_Update_Status.
        /// </summary>
        public static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
    }
}
